name: Build ZMK Firmware

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install west
          sudo apt-get install -y cmake ninja-build gperf ccache dfu-util device-tree-compiler wget
      - name: Initialize west and update
        run: |
          west init -l config
          west update
          west zephyr-export
          west build -s app -d build/left -b nice_nano_v2 -- -DSHIELD=custom_direct_gpio_left
          west build -s app -d build/right -b nice_nano_v2 -- -DSHIELD=custom_direct_gpio_right
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2
